name = "cf"
main = "_worker.js"
compatibility_date = "2023-05-26"
# node_compat = true
workers_dev = false

[[routes]]
pattern = "mmek.rizzzi.us.kg"
custom_domain = true

[vars]
PROXYIP = "103.133.223.50:2096"
UUID = "41a13acc-cec5-41c1-83f5-86d6c08f3f4a"
# SOCKS5 = "127.0.0.1:1080"
# SOCKS5_RELAY = "true"
